language: node_js
node_js:
- '10'
sudo: required
services:
- docker
addons:
  ssh_known_hosts:
  - acai-dev.cornellappdev.com
  - acai-backend.cornellappdev.com
before_install:
- openssl aes-256-cbc -K $encrypted_d17ecc60b00f_key -iv $encrypted_d17ecc60b00f_iv
  -in server.pem.enc -out server.pem -d
jobs:
  include:
  - if: branch = master
    env:
    - NODE_IMAGE="acai-dev"
    - DOMAIN="acai-dev.cornellappdev.com"
  - if: branch = release
    env:
    - NODE_IMAGE="acai"
    - DOMAIN="acai-backend.cornellappdev.com"
deploy:
  provider: script
  script: bash docker_push
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^master|release$"
script:
- 
env:
  global:
  - secure: F6Fl/iWXn+7jHYiR2SlYpfGEPxgoIK8duu6JhFwy2XmZE0UZcEYjLp8ylyZUWSVsk2PiU7Y9FHEk/T1iiUp6DBfRaPSQNyJqaawDgozXB7mAf/i79GiwKjJkd78EryJx8dRquZWOFLAPtbfM/CACmYkjI6U12+aHqD8CvikbqqK44xjKNqNlisLuTFNwK5OST1Y6SZ5XeHu0cHlLuMawGKdFYl9OHtlvyYzJ/nOg5g1zCazsMfBrveY6oxjpGS+UCjN230W9xEMBW4N8zvFxaCN3f9wlRExu4chYkrSSHRxyj6YlQHFxJjEbmyMNktEeCQ5YMztRtEg9FwLkwri6rz9QT060nOGKC7LixpO8Pmic90BHTCPEBx8S7pwPit6F1bGLR3vllZgDFnrGa6sYX5iT/hHshp+OmUGosqkQVKZMDLQZpu7opMIUZXCkrDKyDdhkH9Ls9QiIomoR0Nrz6C6ukYiwTujM9qVmiIUOZ7QiZekB9lYNDpZxMLB04hpHCm3MB6m3t2fAJpRUxu3v7tRUoiSy2d30j+BH2CVNvS8KS04rsnW/GTZzohZEKSAF+3mf+NA2qksZuTKdAq8mijPz1vWvHUB3t5gnqN+rw4SKksnvzt7ryttGd0hJOdu+2ML7LB2/XRE98Q7jakykRtVZWUYk0fRfpA4Ydj2r6rg=
  - secure: ntzzaBbj+EZJKrt8aKqRkJbNPHJlvKc0Il4Wu2zf636j5rtXPJrALF4cv6/RbqVJJ2wN8XW9SMegXh0PdaZQdtdvR0eL1YhyxRdYhaalyT0RxnifB+j/X5xTDV2wWSI/Xt2JbrNwdgT895E/d2SozPBVE0s/qW+Q6gSgQQMMqYTRcFJ/do6QCyxDQlKPWuW/xz1xCPzJSrvB7WHfhd7TXeh3EYJ/tOqzQjyD5BWVS9R7V+COOvUCc8k66GjTt0QBvtP+IUVFKop8V5rFyu9jAF/f/uEuYaSJMZKSrHXX9XSl3GxfnOjt6oZdrXHqI3sibVYbgiilok2dx8Zp2ffJB/iDMg1JQpVaK/qmK978qqokXv9wgO8lxF6N8jDbgkgH1tI5cXA74w6ELYGWLl+m8FrcJQHJ84KAfiymPhVtMCEU7Zp9ueqMDO95zjgNFhOxarqZNKyefgwgFxXFKcBXliX4hHRyln7sGI1/8RaEaHdS1Zc1p7RnvgpM4LHGgP3xu6O0bzVSfUaIi72P5sRK6EuwKusUR7rRDy6aFXPOHrXhVu5nTooqPFZiIwyUQOZazx57muYcX+aP4Izn8xA7I4cKUEt4BB9Y4iKlNsDcjZ9eVHvq7JiaGOUyLpVu2KrisJ05v/LQcK3jVDRtZiyYlik9zSU7WVFUk2d9kR/QWVc=
